//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apcurium.MK.Callbox.Mobile.Client
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int BackgroundSource = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int ButtonStyle = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int HideLogo = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int MvxBind = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int MvxDropDownItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int MvxHttpSource = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int MvxItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int RightButtonSource = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000b
			public const int article_title = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int articlecolor = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int black = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int blue = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int blueback = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int cachecolor = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int darkgray = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int date_color = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int gold = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int gray = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int orange = 2130968576;
			
			// aapt resource value: 0x7f04000d
			public const int red = 2130968589;
			
			// aapt resource value: 0x7f040002
			public const int transparent = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_empty = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int backPickupDestination = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int black_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int close = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int email_cell = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int facebook_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int gray_button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int main_settings = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int navBar = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int newBlackButton = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int orderListBackground = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int password_cell = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int server_button = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int server_button_state = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int sign_in_btn = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int social_media_login_btn = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int social_media_login_btn_hit = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int social_media_login_btn_state = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int splash = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int splash_resizable = 2130837527;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int BackgroundImage = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int ContentLayout = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int ContentSection = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int HeaderSection = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int LoginButton = 2131034132;
			
			// aapt resource value: 0x7f05000f
			public const int LogoutButton = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int MainLogo = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindableListItemTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int MyButton = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int NavBarImage = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int NavBarSection = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int NavBarSectionBackground = 2131034115;
			
			// aapt resource value: 0x7f050019
			public const int OrderList = 2131034137;
			
			// aapt resource value: 0x7f050013
			public const int Password = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int ServerButton = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int Username = 2131034130;
			
			// aapt resource value: 0x7f050005
			public const int ViewNavBarRightButton = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ViewTitle = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int cancelOrderButton = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int dateTextView = 2131034122;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout0 = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int listTitle = 2131034135;
			
			// aapt resource value: 0x7f05000b
			public const int orderNumberTextView = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int orderStatusTextView = 2131034124;
			
			// aapt resource value: 0x7f050018
			public const int stroke = 2131034136;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Control_HeaderedLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Control_OrderCell = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int View_CallTaxi = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int View_Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int View_OrderList = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int BookTaxiPassengerName = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int BookTaxiTitle = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int Callbox_passengerName = 2131099659;
			
			// aapt resource value: 0x7f060015
			public const int CancelOrderMessage = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int CancelOrderTitle = 2131099668;
			
			// aapt resource value: 0x7f06000a
			public const int CarAssigned = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int EmailLabel = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int Language = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int LanguageCode = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int LoadingMessage = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int LogoutMessage = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int LogoutTitle = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int No = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int NoPickupAddress = 2131099670;
			
			// aapt resource value: 0x7f06000f
			public const int Ok = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int OrderNote = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int PasswordLabel = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int PushTaxi = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int SignInButton = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int View_SignIn = 2131099653;
			
			// aapt resource value: 0x7f060010
			public const int Yes = 2131099664;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f07000c
			public const int BigTitleText = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int BigTitleTextBlack = 2131165199;
			
			// aapt resource value: 0x7f070003
			public const int ButtonText = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int ButtonTextGray = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int ButtonTextLarge = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int CallboxButtonText = 2131165188;
			
			// aapt resource value: 0x7f070014
			public const int DetailText = 2131165204;
			
			// aapt resource value: 0x7f07000e
			public const int FinePrint = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int FormLabelText = 2131165186;
			
			// aapt resource value: 0x7f070011
			public const int GrayText = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int HeaderGroupTitle = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int LinkText = 2131165185;
			
			// aapt resource value: 0x7f070015
			public const int ListItemLabel = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int ListItemSpinnerValue = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int ListItemValue = 2131165206;
			
			// aapt resource value: 0x7f070009
			public const int ListSubTitle = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int ListTitle = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int SearchButtonText = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int SimpleText = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int SimpleTextItem = 2131165202;
			
			// aapt resource value: 0x7f07000d
			public const int SmallTitle = 2131165197;
			
			// aapt resource value: 0x7f070019
			public const int Theme_Modal = 2131165209;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			// aapt resource value: 0x7f070018
			public const int Theme_Transparent = 2131165208;
			
			// aapt resource value: 0x7f07000a
			public const int TitleText = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int ViewTitleStyle = 2131165195;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public const int MvxBindableListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			public static int[] apcurium_mk_callbox_mobile_client_controls_HeaderedLayout = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int apcurium_mk_callbox_mobile_client_controls_HeaderedLayout_BackgroundSource = 2;
			
			// aapt resource value: 0
			public const int apcurium_mk_callbox_mobile_client_controls_HeaderedLayout_HideLogo = 0;
			
			// aapt resource value: 1
			public const int apcurium_mk_callbox_mobile_client_controls_HeaderedLayout_RightButtonSource = 1;
			
			public static int[] apcurium_mk_callbox_mobile_client_controls_StyledButton = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public const int apcurium_mk_callbox_mobile_client_controls_StyledButton_ButtonStyle = 0;
			
			private Styleable()
			{
			}
		}
	}
}
