//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apcurium.MK.Booking.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CheckerYellowCabPalmetto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckerYellowCabPalmetto() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("apcurium.MK.Booking.Resources.CheckerYellowCabPalmetto", typeof(CheckerYellowCabPalmetto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  CARD ON FILE.
        /// </summary>
        internal static string CardOnFile {
            get {
                return ResourceManager.GetString("CardOnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  CHARGE ACCOUNT.
        /// </summary>
        internal static string ChargeAccount {
            get {
                return ResourceManager.GetString("ChargeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  PAYMENT IN CAR.
        /// </summary>
        internal static string PaymentInCar {
            get {
                return ResourceManager.GetString("PaymentInCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  PAYPAL.
        /// </summary>
        internal static string PayPal {
            get {
                return ResourceManager.GetString("PayPal", resourceCulture);
            }
        }
    }
}
