// <auto-generated />
namespace apcurium.MK.Common.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Configuration_Fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Configuration_Fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201511031810360_Configuration_Fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
