// <auto-generated />
namespace apcurium.MK.Booking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Booking_Mears_Aug3_2016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Booking_Mears_Aug3_2016));
        
        string IMigrationMetadata.Id
        {
            get { return "201608031804420_Booking_Mears_Aug3_2016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
