// <auto-generated />
namespace apcurium.MK.Booking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Booking_MKTAXI3654 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Booking_MKTAXI3654));
        
        string IMigrationMetadata.Id
        {
            get { return "201602032237485_Booking_MKTAXI-3654"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
