// <auto-generated />
namespace apcurium.MK.Booking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Booking_MKTAXI_3815_3654_3823 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Booking_MKTAXI_3815_3654_3823));
        
        string IMigrationMetadata.Id
        {
            get { return "201602081528103_Booking_MKTAXI_3815_3654_3823"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
