namespace apcurium.MK.Booking.MapDataProvider.Google.Resources	
{
    public enum AddressComponentType
    {
        Street_address,
        Route,
        Intersection,
        Political,
        Country,
        Administrative_area_level_1,
        Administrative_area_level_2,
        Administrative_area_level_3,
        Colloquial_area,
        Locality,
        Sublocality,
        Neighborhood,
        Premise,
        Subpremise,
        Postal_code,
        Natural_feature,
        Airport,
        Park,
        Bus_station,
        Transit_station,
        Point_of_interest,
        Post_box,
        Street_number,
        Floor,
        Room,
        Unkown,
    }
}