// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TaxiMobile.Book {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("PickupLocationView")]
	public partial class PickupLocationView {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITextField __mt_txtAddress;
		
		private MonoTouch.UIKit.UITextField __mt_txtAptSuite;
		
		private MonoTouch.UIKit.UITextField __mt_txtRingCode;
		
		private MonoTouch.UIKit.UITextField __mt_txtTime;
		
		private MonoTouch.MapKit.MKMapView __mt_mapPickUp;
		
		private MonoTouch.UIKit.UIButton __mt_btnPickAddress;
		
		private MonoTouch.UIKit.UIImageView __mt_imageFieldBackground;
		
		private MonoTouch.UIKit.UITableView __mt_tableAddress;
		
		private MonoTouch.UIKit.UILabel __mt_lblDestination;
		
		private MonoTouch.UIKit.UILabel __mt_lblPickup;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtAddress")]
		private MonoTouch.UIKit.UITextField txtAddress {
			get {
				this.__mt_txtAddress = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtAddress")));
				return this.__mt_txtAddress;
			}
			set {
				this.__mt_txtAddress = value;
				this.SetNativeField("txtAddress", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtAptSuite")]
		private MonoTouch.UIKit.UITextField txtAptSuite {
			get {
				this.__mt_txtAptSuite = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtAptSuite")));
				return this.__mt_txtAptSuite;
			}
			set {
				this.__mt_txtAptSuite = value;
				this.SetNativeField("txtAptSuite", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtRingCode")]
		private MonoTouch.UIKit.UITextField txtRingCode {
			get {
				this.__mt_txtRingCode = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtRingCode")));
				return this.__mt_txtRingCode;
			}
			set {
				this.__mt_txtRingCode = value;
				this.SetNativeField("txtRingCode", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtTime")]
		private MonoTouch.UIKit.UITextField txtTime {
			get {
				this.__mt_txtTime = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtTime")));
				return this.__mt_txtTime;
			}
			set {
				this.__mt_txtTime = value;
				this.SetNativeField("txtTime", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("mapPickUp")]
		private MonoTouch.MapKit.MKMapView mapPickUp {
			get {
				this.__mt_mapPickUp = ((MonoTouch.MapKit.MKMapView)(this.GetNativeField("mapPickUp")));
				return this.__mt_mapPickUp;
			}
			set {
				this.__mt_mapPickUp = value;
				this.SetNativeField("mapPickUp", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnPickAddress")]
		private MonoTouch.UIKit.UIButton btnPickAddress {
			get {
				this.__mt_btnPickAddress = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnPickAddress")));
				return this.__mt_btnPickAddress;
			}
			set {
				this.__mt_btnPickAddress = value;
				this.SetNativeField("btnPickAddress", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageFieldBackground")]
		private MonoTouch.UIKit.UIImageView imageFieldBackground {
			get {
				this.__mt_imageFieldBackground = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageFieldBackground")));
				return this.__mt_imageFieldBackground;
			}
			set {
				this.__mt_imageFieldBackground = value;
				this.SetNativeField("imageFieldBackground", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tableAddress")]
		private MonoTouch.UIKit.UITableView tableAddress {
			get {
				this.__mt_tableAddress = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("tableAddress")));
				return this.__mt_tableAddress;
			}
			set {
				this.__mt_tableAddress = value;
				this.SetNativeField("tableAddress", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblDestination")]
		private MonoTouch.UIKit.UILabel lblDestination {
			get {
				this.__mt_lblDestination = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblDestination")));
				return this.__mt_lblDestination;
			}
			set {
				this.__mt_lblDestination = value;
				this.SetNativeField("lblDestination", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblPickup")]
		private MonoTouch.UIKit.UILabel lblPickup {
			get {
				this.__mt_lblPickup = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblPickup")));
				return this.__mt_lblPickup;
			}
			set {
				this.__mt_lblPickup = value;
				this.SetNativeField("lblPickup", value);
			}
		}
	}
}
