// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace apcurium.MK.Booking.Mobile.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Taxiworld {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Taxiworld() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("apcurium.MK.Booking.Mobile.Localization.Taxiworld", typeof(Taxiworld).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BookItButton {
            get {
                return ResourceManager.GetString("BookItButton", resourceCulture);
            }
        }
        
        internal static string AptNumber {
            get {
                return ResourceManager.GetString("AptNumber", resourceCulture);
            }
        }
        
        internal static string NoAptText {
            get {
                return ResourceManager.GetString("NoAptText", resourceCulture);
            }
        }
        
        internal static string EntryCodeLabel {
            get {
                return ResourceManager.GetString("EntryCodeLabel", resourceCulture);
            }
        }
        
        internal static string ApartmentLabel {
            get {
                return ResourceManager.GetString("ApartmentLabel", resourceCulture);
            }
        }
        
        internal static string NbPassenger {
            get {
                return ResourceManager.GetString("NbPassenger", resourceCulture);
            }
        }
        
        internal static string NbPassengers {
            get {
                return ResourceManager.GetString("NbPassengers", resourceCulture);
            }
        }
        
        internal static string DateTimePickerSetButton {
            get {
                return ResourceManager.GetString("DateTimePickerSetButton", resourceCulture);
            }
        }
        
        internal static string CreditCardZipCode {
            get {
                return ResourceManager.GetString("CreditCardZipCode", resourceCulture);
            }
        }
        
        internal static string HistoryDetailAptRingCodeLabel {
            get {
                return ResourceManager.GetString("HistoryDetailAptRingCodeLabel", resourceCulture);
            }
        }
    }
}
