// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace apcurium.MK.Booking.Mobile.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Taxi {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Taxi() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("apcurium.MK.Booking.Mobile.Taxi", typeof(Taxi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string EtaNoTaxiAvailable {
            get {
                return ResourceManager.GetString("EtaNoTaxiAvailable", resourceCulture);
            }
        }
        
        public static string Eta {
            get {
                return ResourceManager.GetString("Eta", resourceCulture);
            }
        }
        
        public static string ManualPairingForRideLinQ_Instructions {
            get {
                return ResourceManager.GetString("ManualPairingForRideLinQ_Instructions", resourceCulture);
            }
        }
        
        public static string DriverBonusDescription {
            get {
                return ResourceManager.GetString("DriverBonusDescription", resourceCulture);
            }
        }
        
        public static string DriverInfoTaxiType {
            get {
                return ResourceManager.GetString("DriverInfoTaxiType", resourceCulture);
            }
        }
        
        public static string ManualRideLinqStatus_PairingError_Luxury {
            get {
                return ResourceManager.GetString("ManualRideLinqStatus_PairingError_Luxury", resourceCulture);
            }
        }
        
        public static string CarAssigned {
            get {
                return ResourceManager.GetString("CarAssigned", resourceCulture);
            }
        }
        
        public static string MarketChangedMessage {
            get {
                return ResourceManager.GetString("MarketChangedMessage", resourceCulture);
            }
        }
        
        public static string EtaNoTaxiAvailable_Luxury {
            get {
                return ResourceManager.GetString("EtaNoTaxiAvailable_Luxury", resourceCulture);
            }
        }
        
        public static string HomeView_BookTaxi_Luxury {
            get {
                return ResourceManager.GetString("HomeView_BookTaxi_Luxury", resourceCulture);
            }
        }
        
        public static string BookingGratuityText {
            get {
                return ResourceManager.GetString("BookingGratuityText", resourceCulture);
            }
        }
        
        public static string MarketChangedMessage_Luxury {
            get {
                return ResourceManager.GetString("MarketChangedMessage_Luxury", resourceCulture);
            }
        }
        
        public static string HomeView_ManualPairing {
            get {
                return ResourceManager.GetString("HomeView_ManualPairing", resourceCulture);
            }
        }
        
        public static string GratuitActivityName {
            get {
                return ResourceManager.GetString("GratuitActivityName", resourceCulture);
            }
        }
        
        public static string EtaLessThanAMinute {
            get {
                return ResourceManager.GetString("EtaLessThanAMinute", resourceCulture);
            }
        }
        
        public static string EtaLessThanAMinute_Luxury {
            get {
                return ResourceManager.GetString("EtaLessThanAMinute_Luxury", resourceCulture);
            }
        }
        
        public static string StatusConfirmNewBooking_Luxury {
            get {
                return ResourceManager.GetString("StatusConfirmNewBooking_Luxury", resourceCulture);
            }
        }
        
        public static string HomeView_BookTaxi {
            get {
                return ResourceManager.GetString("HomeView_BookTaxi", resourceCulture);
            }
        }
        
        public static string StatusConfirmNewBooking {
            get {
                return ResourceManager.GetString("StatusConfirmNewBooking", resourceCulture);
            }
        }
        
        public static string ManualRideLinqStatus_PairingError {
            get {
                return ResourceManager.GetString("ManualRideLinqStatus_PairingError", resourceCulture);
            }
        }
        
        public static string ReminderDetails_Luxury {
            get {
                return ResourceManager.GetString("ReminderDetails_Luxury", resourceCulture);
            }
        }
        
        public static string Gratuity_Pay {
            get {
                return ResourceManager.GetString("Gratuity_Pay", resourceCulture);
            }
        }
        
        public static string ReminderDetails {
            get {
                return ResourceManager.GetString("ReminderDetails", resourceCulture);
            }
        }
        
        public static string Eta_Luxury {
            get {
                return ResourceManager.GetString("Eta_Luxury", resourceCulture);
            }
        }
    }
}
